#!/bin/bash
python Feed_SRSN.py -m debug 
python Feed_SRSN.py -m debug 
python Feed_SRSN.py -m debug 
python Feed_SRSN.py -m debug
python Feed_SRSN.py -m debug
python Feed_SRSN.py -m debug
python Feed_SRSN.py -m debug
python Feed_SRSN.py -m debug
python Feed_SRSN.py -m debug
