#!/bin/bash
python SRSN_RRDB.py -m debug 
python SRSN_RRDB.py -m debug 
python SRSN_RRDB.py -m debug 
python SRSN_RRDB.py -m debug 
python SRSN_RRDB.py -m debug 
python SRSN_RRDB.py -m debug 
python SRSN_RRDB.py -m debug 
python SRSN_RRDB.py -m debug 
python SRSN_RRDB.py -m debug 
python SRSN_RRDB.py -m debug 
python SRSN_RRDB.py -m debug 
python SRSN_RRDB.py -m debug 
python SRSN_RRDB.py -m debug 

