#!/bin/bash
python SRSN.py -m debug 
python SRSN.py -m debug 
python SRSN.py -m debug 
python SRSN.py -m debug
python SRSN.py -m debug
python SRSN.py -m debug
python SRSN.py -m debug
python SRSN.py -m debug
python SRSN.py -m debug
